apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name:  al357bluflask
  namespace: al357blu
  labels: 
    app:  al357bluflask 
spec: 
  selector: 
    matchLabels: 
      app: al357bluflask 
  replicas: 1 
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app:  al357bluflask 
    spec: 
      containers: 
      - name:  al357blu 
        image:  al357blu/flask_app 
        resources: 
          requests: 
            cpu: 100m 
            memory: 100Mi 
          limits: 
            cpu: 100m 
            memory: 100Mi 
        ports: 
        - containerPort:  5000 
          name:  al357bluflask 
        imagePullPolicy: Always 
      restartPolicy: Always 
 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: al357bluflask 
  namespace: al357blu
spec: 
  selector: 
    app: al357bluflask 
  type: LoadBalancer 
  sessionAffinity: None 
  sessionAffinityConfig: 
    clientIP: 
      timeoutSeconds: 10800 
  ports: 
  - name: al357bluflask
    protocol: TCP 
    port: 80 
    targetPort: 5000 