apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-deployment
  labels:
    app: flask

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask

    spec:
      containers:
      - name:  flask
        image: al357blu/flask_app
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
spec:
  selector:
    app: flask
  type: LoadBalancer
  ports:
  - name: flask
    protocol: TCP
    port: 80
    targetPort: 5000      
  
